### ISSUE TITLE
MNEMONIC="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" INFURA_PROJECT_ID="<Your Infura Project ID>" GANACHE_MNEMONIC="<Your Ganache Mnemonic>" KOVAN_MNEMONIC="<Your Kovan Mnemonic>"

### ISSUE THREAD

**Issue by daishiydmaguchi** [truffle-box/optimism-box#12]
MNEMONIC="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
INFURA_PROJECT_ID="<Your Infura Project ID>"
GANACHE_MNEMONIC="<Your Ganache Mnemonic>"
KOVAN_MNEMONIC="<Your Kovan Mnemonic>"

**Comment by fainashalts** [comment]
Hi @daishiydmaguchi can you let me know if you have an issue that needs addressing? Thanks so much!

**Comment by fainashalts** [comment]
Hi @daishiydmaguchi I'm closing this for issue maintenance but please let me know if you have an issue I need to look into. Thanks!
