### ISSUE TITLE
when trying to use the npm runLocalOptimism command

### ISSUE THREAD

**Issue by MathiusEire** [truffle-box/optimism-box#14]
when trying to use the npm runLocalOptimism command im returned with :
Unknown command: "runLocalOptimism"

Did you mean one of these?
    npm run startLocalOptimism # run the "startLocalOptimism" package script
    npm run stopLocalOptimism # run the "stopLocalOptimism" package script

To see a list of supported npm commands, run:
  npm help

any ideas?

**Comment by fainashalts** [comment]
Hi @MathiusEire my apologies for any confusion! I have updated the note in `truffle-config.ovm.js`. The steps are laid out in the readme. If you have never run the localOptimism node before, you will first run `npm run installLocalOptimism`. This one will take several minutes but you should only have to run it once. 

Then, when you want to run the node locally, you should use `npm run startLocalOptimism` to start the node and `npm run stopLocalOptimism` to gracefully shut it down. 

I hope that helps! I'm closing this issue as this note should address your question, but please feel free to open a new issue if there is something I've left unclear. Thank you for bringing this to my attention!
