### ISSUE TITLE
Is this box still needed?

### ISSUE THREAD

**Issue by qbzzt** [truffle-box/optimism-box#23]
Ever since the regenesis on November 11th, 2021, [you don't need to do anything special to use Optimism with Truffle](https://github.com/ethereum-optimism/optimism-tutorial/blob/main/getting-started/README.md#truffle). I don't think we still need this box.

**Comment by fainashalts** [comment]
Hi @qbzzt! Technically you can compile and deploy without needing to do anything special, but I think it helps to have an idea of how to organize a project that spans both Optimism and Mainnet. We'll be coming out with a bridging example box soon that builds on this box.

We also don't really have a process for deprecating boxes, something we will be working out soon. So for now I'd like to keep this live and ensure that it is up to date. If you think there's anything I should update please let me know and I'll take care of it!

**Comment by qbzzt** [comment]
I love the idea of a bridging example box, [you might find this tutorial useful](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge).

If you want to show additional SDKs in the box, we can now [estimate gas costs](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/sdk-estimate-gas) and [trace bridged transactions](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/sdk-view-tx).

**Comment by fainashalts** [comment]
Oh very cool! Thanks @qbzzt. Would love to have you try it out when it's ready.

**Comment by qbzzt** [comment]
Tell me when it's available and I'll QA it. Warning: I tend to break stuff.
